/**
 * Stripe Products Configuration
 *
 * Auto-generated by scripts/fetch-stripe-prices.ts
 * Generated: 2026-02-06T20:54:24.687Z
 *
 * DO NOT EDIT MANUALLY - Run the script to regenerate
 */

export const STRIPE_PRODUCTS = {
  subscriptions: {
    starter: {
      productId: 'prod_TvnNymcXzhc72C',
      priceId: 'price_1SxvmOBrdEbWXxivKSBtIBuz',
      name: 'M3 Starter',
      price: 14999, // cents ($149.99)
      interval: 'month',
      sessionsPerWeek: 1,
      description: 'Perfect for getting started — 1 session per week',
    },
    foundation: {
      productId: 'prod_TvnMGe1FCecHDO',
      priceId: 'price_1SxvlfBrdEbWXxivUsc2kzab',
      name: 'M3 Foundation',
      price: 24999, // cents ($249.99)
      interval: 'month',
      sessionsPerWeek: 2,
      description: 'Build your foundation — 2 sessions per week',
    },
    elite: {
      productId: 'prod_TvnM6RHFL8I50N',
      priceId: 'price_1SxvlgBrdEbWXxivY2RQwxCK',
      name: 'M3 Elite',
      price: 69900, // cents ($699.00)
      interval: 'month',
      sessionsPerWeek: -1,
      description: 'Unlimited sessions for serious athletes',
    },
    competitor: {
      productId: 'prod_TvnMWFpXOkd9WB',
      priceId: 'price_1SxvlfBrdEbWXxivEmiPpSNy',
      name: 'M3 Competitor',
      price: 44900, // cents ($449.00)
      interval: 'month',
      sessionsPerWeek: 3,
      description: 'Compete at the next level — 3 sessions per week',
    }
  },
  oneTime: {
    tenPack: {
      productId: 'prod_TvnO8Rk82fS9Ho',
      priceId: 'price_1SxvnuBrdEbWXxivlnIOi4tN',
      name: '10-Pack x1hr',
      price: 44999, // cents ($449.99)
      sessions: 10,
      description: '10 training sessions — best value',
    },
    fivePack: {
      productId: 'prod_TvnNlbvhpW4lhc',
      priceId: 'price_1SxvmyBrdEbWXxiv8LaurKDy',
      name: '5-Pack x 1hr',
      price: 23500, // cents ($235.00)
      sessions: 5,
      description: '5 training sessions — save $140',
    },
    dropIn: {
      productId: 'prod_TvnMzL5yV4cMbN',
      priceId: 'price_1SxvlgBrdEbWXxiv8jcoXYka',
      name: 'Drop-in Session',
      price: 7500, // cents ($75.00)
      sessions: 1,
      description: '1-hour training session',
    }
  },
} as const;

export type SubscriptionTier = keyof typeof STRIPE_PRODUCTS.subscriptions;
export type OneTimePurchase = keyof typeof STRIPE_PRODUCTS.oneTime;

// Helper to get all subscription tiers as array
export const SUBSCRIPTION_TIERS = Object.keys(STRIPE_PRODUCTS.subscriptions) as SubscriptionTier[];

// Helper to get all one-time purchases as array
export const ONE_TIME_PURCHASES = Object.keys(STRIPE_PRODUCTS.oneTime) as OneTimePurchase[];

// Price lookup helpers
export function getSubscriptionPrice(tier: SubscriptionTier) {
  return STRIPE_PRODUCTS.subscriptions[tier];
}

export function getOneTimePrice(purchase: OneTimePurchase) {
  return STRIPE_PRODUCTS.oneTime[purchase];
}

// Get price ID by product type and key
export function getPriceId(type: 'subscription' | 'oneTime', key: string): string | null {
  if (type === 'subscription' && key in STRIPE_PRODUCTS.subscriptions) {
    return STRIPE_PRODUCTS.subscriptions[key as SubscriptionTier].priceId;
  }
  if (type === 'oneTime' && key in STRIPE_PRODUCTS.oneTime) {
    return STRIPE_PRODUCTS.oneTime[key as OneTimePurchase].priceId;
  }
  return null;
}
